import { Platform, StyleSheet } from 'react-native';

import { colors, radius, shadow, spacing } from '@/src/shared/theme';

export const styles = StyleSheet.create({
  content: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  categoryTabs: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  categoryTab: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    flex: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: spacing.md,
    ...shadow,
  },
  categoryText: {
    color: colors.textSoft,
    fontSize: 14,
    fontWeight: '900',
  },
  categoryTextSelected: {
    color: '#fff',
  },
  quickAdd: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  quickInput: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    color: colors.text,
    flex: 1,
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: spacing.lg,
    ...shadow,
  },
  addButton: {
    alignItems: 'center',
    borderRadius: radius.lg,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  disabled: {
    opacity: 0.45,
  },
  selectedDateRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  selectedDateText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  clearDate: {
    color: colors.primaryDark,
    fontSize: 12,
    fontWeight: '900',
  },
  todoList: {
    gap: spacing.md,
    marginBottom: spacing.xl,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    gap: spacing.xs,
    padding: spacing.xl,
    ...shadow,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  emptyText: {
    color: colors.muted,
    fontSize: 13,
    textAlign: 'center',
  },
  todoCard: {
    borderRadius: radius.xl,
    overflow: 'hidden',
    position: 'relative',
  },
  todoDeleteAction: {
    alignItems: 'center',
    backgroundColor: colors.danger,
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    top: 0,
    width: 92,
  },
  todoDeleteText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '900',
  },
  todoCardSurface: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderWidth: 1,
    ...shadow,
  },
  todoHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.md,
  },
  checkCircle: {
    alignItems: 'center',
    borderColor: colors.faint,
    borderRadius: 12,
    borderWidth: 2,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  todoMain: {
    flex: 1,
    gap: spacing.xs,
  },
  todoTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 22,
  },
  todoCompleted: {
    color: colors.faint,
    textDecorationLine: 'line-through',
  },
  metaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  metaText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  dueTag: {
    borderRadius: radius.sm,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
  },
  tagToday: {
    backgroundColor: colors.successSoft,
    color: colors.success,
  },
  tagTomorrow: {
    backgroundColor: colors.primarySoft,
    color: colors.primary,
  },
  tagOverdue: {
    backgroundColor: colors.dangerSoft,
    color: colors.danger,
  },
  detailForm: {
    backgroundColor: colors.surfaceMuted,
    borderTopColor: colors.border,
    borderTopWidth: 1,
    padding: spacing.md,
  },
  formRow: {
    flexDirection: Platform.OS === 'web' ? 'row' : 'column',
    gap: spacing.md,
  },
  formColumn: {
    flex: 1,
  },
  formActions: {
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'flex-end',
    marginTop: spacing.xl,
    paddingBottom: spacing.md,
  },
  fab: {
    position: 'absolute',
    bottom: 32,
    right: 24,
    width: 64,
    height: 64,
    borderRadius: 32,
    ...shadow,
    elevation: 8,
    zIndex: 100,
  },
  fabGradient: {
    flex: 1,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomSheetBg: {
    backgroundColor: colors.surface,
    borderRadius: 24,
  },
  bottomSheetIndicator: {
    backgroundColor: colors.border,
    width: 48,
    height: 6,
    borderRadius: 3,
  },
  sheetTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: colors.text,
  },
  modalContent: {
    padding: spacing.xl,
    paddingBottom: spacing.xxl,
  },
  calendarCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.md,
    ...shadow,
  },
  calendarHeader: {
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  calendarTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  monthControl: {
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.lg,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xs,
  },
  monthText: {
    color: colors.textSoft,
    fontSize: 15,
    fontWeight: '900',
  },
  weekRow: {
    flexDirection: 'row',
  },
  weekText: {
    color: colors.muted,
    flex: 1,
    fontSize: 11,
    fontWeight: '900',
    paddingBottom: spacing.sm,
    textAlign: 'center',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 1,
  },
  dayCell: {
    backgroundColor: colors.bg,
    borderRadius: radius.sm,
    minHeight: 58,
    padding: 5,
    width: '14.08%',
  },
  dayCellSelected: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
    borderWidth: 1,
  },
  dayCellMuted: {
    opacity: 0.45,
  },
  dayNumber: {
    alignSelf: 'flex-end',
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 20,
    textAlign: 'center',
    width: 20,
  },
  todayNumber: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    color: '#fff',
    overflow: 'hidden',
  },
  selectedDayNumber: {
    color: colors.primaryDark,
  },
  dayTodoDots: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 3,
    marginTop: 'auto',
  },
  dayTodoDot: {
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  moreDots: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: '900',
  },
});
