import { StyleSheet } from 'react-native';

import { colors, radius, shadow, spacing } from '@/src/shared/theme';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  content: { gap: spacing.md, padding: spacing.lg, paddingBottom: spacing.xxl },
  card: { backgroundColor: colors.surface, borderRadius: radius.xl, gap: spacing.md, padding: spacing.lg, ...shadow },
  innerCard: { backgroundColor: colors.surfaceMuted, elevation: 0, shadowOpacity: 0 },
  selectedCard: { borderColor: colors.primary, borderWidth: 1 },
  completedCard: { backgroundColor: colors.successSoft },
  row: { alignItems: 'center', flexDirection: 'row', gap: spacing.md },
  rowTop: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md, justifyContent: 'space-between' },
  rowWrap: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  modalContent: { padding: spacing.lg, paddingBottom: spacing.xxl },
  iconColumn: { alignItems: 'center', gap: spacing.xs },
  itemTitle: { color: colors.text, fontSize: 17, fontWeight: '900', lineHeight: 23 },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '900' },
  bodyText: { color: colors.textSoft, fontSize: 14, lineHeight: 21 },
  metaText: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  emptyText: { color: colors.muted, fontSize: 14, lineHeight: 20, textAlign: 'center' },
  emojiImage: { width: 34, height: 34 },
  bigEmojiImage: { width: 34, height: 34 },
  timeline: { gap: spacing.md },
  splitStack: { gap: spacing.md },
  tagRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  tag: { alignSelf: 'flex-start', borderRadius: radius.sm, fontSize: 11, fontWeight: '900', overflow: 'hidden', paddingHorizontal: spacing.sm, paddingVertical: 3 },
  tag_gray: { backgroundColor: colors.surfaceMuted, color: colors.textSoft },
  tag_blue: { backgroundColor: colors.primarySoft, color: colors.primary },
  tag_green: { backgroundColor: colors.successSoft, color: colors.success },
  tag_red: { backgroundColor: colors.dangerSoft, color: colors.danger },
  tag_purple: { backgroundColor: '#F3E8FF', color: '#7E22CE' },
  tag_orange: { backgroundColor: colors.warningSoft, color: colors.warning },
  staffCard: { backgroundColor: '#FBFAFF' },
  staff: { height: 220, position: 'relative' },
  staffCurve: { left: 0, position: 'absolute', top: 0 },
  staffLine: { backgroundColor: '#DDD6FE', height: 1, marginTop: 34, opacity: 0.8 },
  staffPoint: { alignItems: 'center', position: 'absolute', width: 42, gap: 4 },
  staffEmoji: { fontSize: 24 },
  staffEmojiImage: { width: 24, height: 24 },
  staffTime: { color: colors.faint, fontSize: 9, textAlign: 'center' },
  moodPicker: { flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between', marginBottom: spacing.xl },
  moodButton: { flex: 1, alignItems: 'center', backgroundColor: colors.surfaceMuted, borderRadius: radius.lg, paddingVertical: spacing.md, paddingHorizontal: spacing.xs, borderWidth: 2, borderColor: 'transparent' },
  moodButtonSelected: { backgroundColor: '#F3E8FF', borderColor: '#C084FC' },
  moodLabel: { color: colors.textSoft, fontSize: 12, fontWeight: '800' },
  formLabel: { color: colors.textSoft, fontSize: 13, fontWeight: '900', marginBottom: spacing.sm },
  pills: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.md },
  pill: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 9999, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  pillSelected: { backgroundColor: colors.text, borderColor: colors.text },
  pillText: { color: colors.textSoft, fontSize: 13, fontWeight: '800' },
  pillTextSelected: { color: '#fff' },
  miniMood: { alignItems: 'center', borderRadius: 9999, height: 40, justifyContent: 'center', width: 40 },
  input: { backgroundColor: colors.surfaceMuted, borderRadius: radius.lg, color: colors.text, fontSize: 16, minHeight: 52, paddingHorizontal: spacing.lg },
  textArea: { minHeight: 150, paddingTop: spacing.md },
  formRow: { flexDirection: 'row', gap: spacing.md },
  formActions: { flexDirection: 'row', gap: spacing.md, justifyContent: 'flex-end', marginTop: spacing.xl, paddingBottom: spacing.md },
  group: { gap: spacing.md },
  groupTitle: { color: colors.textSoft, fontSize: 14, fontWeight: '900' },
  detailBlock: { borderTopColor: colors.border, borderTopWidth: 1, gap: spacing.md, marginTop: spacing.md, paddingTop: spacing.md },
  detail: { borderRadius: radius.md, gap: spacing.xs, padding: spacing.md },
  detail_gray: { backgroundColor: colors.surfaceMuted },
  detail_green: { backgroundColor: colors.successSoft },
  detail_red: { backgroundColor: colors.dangerSoft },
  detail_blue: { backgroundColor: colors.primarySoft },
  detailLabel: { color: colors.textSoft, fontSize: 12, fontWeight: '900' },
  statsGrid: { gap: spacing.md },
  statCard: { gap: spacing.xs },
  statLabel: { color: colors.muted, fontSize: 12, fontWeight: '900' },
  statValue: { color: colors.text, fontSize: 26, fontWeight: '900' },
  metricLine: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md },
  metricValue: { color: colors.text, fontSize: 13, fontWeight: '900' },
  progressTrack: { backgroundColor: colors.surfaceMuted, borderRadius: 9999, height: 10, overflow: 'hidden' },
  progressFill: { borderRadius: 9999, height: '100%' },
  quickAdd: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  quickInput: { backgroundColor: colors.surface, borderRadius: radius.lg, color: colors.text, flex: 1, fontSize: 16, minHeight: 52, paddingHorizontal: spacing.lg, ...shadow },
  addButton: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: radius.lg, height: 52, justifyContent: 'center', width: 52 },
  checkCircle: { alignItems: 'center', borderColor: colors.faint, borderRadius: 12, borderWidth: 2, height: 24, justifyContent: 'center', width: 24 },
  checkCircleDone: { backgroundColor: colors.primary, borderColor: colors.primary },
  completedText: { color: colors.faint, textDecorationLine: 'line-through' },
  footprintImage: { backgroundColor: colors.border, borderRadius: radius.lg, height: 180, marginTop: spacing.md, width: '100%' },
  previewImage: { backgroundColor: colors.border, borderRadius: radius.lg, height: 220, width: '100%' },
  fullImageBackdrop: { alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.9)', flex: 1, justifyContent: 'center', padding: spacing.lg },
  fullImage: { height: '90%', width: '100%' },
  fab: { position: 'absolute', bottom: 32, right: 24, width: 64, height: 64, borderRadius: 32, ...shadow, elevation: 8, zIndex: 100 },
  fabGradient: { flex: 1, borderRadius: 32, justifyContent: 'center', alignItems: 'center' },
  bottomSheetBg: { backgroundColor: colors.surface, borderRadius: 24 },
  bottomSheetIndicator: { backgroundColor: colors.border, width: 48, height: 6, borderRadius: 3 },
  sheetTitle: { fontSize: 22, fontWeight: '900', color: colors.text },
});
