import { Platform, StyleSheet } from 'react-native';

import { colors, radius, shadow, spacing } from '@/src/shared/theme';

export const styles = StyleSheet.create({
  header: {
    paddingTop: Platform.OS === 'ios' ? 54 : spacing.xl,
    paddingBottom: spacing.xs,
  },
  flex: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  headerInfo: {
    marginBottom: spacing.xl,
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: '900',
    color: colors.text,
    marginBottom: spacing.xs,
  },
  pageSubtitle: {
    fontSize: 14,
    color: colors.textSoft,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 0,
  },
  datePickerWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  datePickerLabel: {
    fontSize: 12,
    color: colors.muted,
    marginRight: 6,
  },
  datePickerInput: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
    width: 66,
    padding: 0,
    margin: 0,
    textAlign: 'center',
  },
  grid: {
    gap: spacing.sm,
  },
  statCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
  },
  statLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textSoft,
    marginBottom: spacing.xs,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '900',
    color: colors.text,
  },
  statValueBig: {
    fontSize: 28,
    fontWeight: '900',
    color: colors.text,
  },
  statNote: {
    fontSize: 11,
    color: colors.muted,
    marginTop: spacing.xs,
  },
  statCardSmallRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  statCardSmall: {
    flex: 1,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.lg,
    padding: spacing.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  statLabelSmall: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSoft,
    marginBottom: 2,
  },
  statValueSmall: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.text,
  },
  categoryCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
  },
  categoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  categoryBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: radius.full,
  },
  categoryBadgeText: {
    fontSize: 12,
    fontWeight: '800',
  },
  categoryStatsRow: {
    flexDirection: 'row',
    gap: spacing.lg,
    marginBottom: spacing.md,
  },
  categoryStatCol: {
    flex: 1,
  },
  categoryStatLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSoft,
    marginBottom: 2,
    textTransform: 'uppercase',
  },
  categoryStatValue: {
    fontSize: 22,
    fontWeight: '900',
    color: colors.text,
  },
  categoryProjectionRow: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categoryProjectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSoft,
  },
  categoryProjectionValue: {
    fontSize: 24,
    fontWeight: '900',
    color: '#2563eb',
  },
  chartFilterScroll: {
    gap: spacing.sm,
    paddingBottom: spacing.sm,
  },
  chartFilterBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  chartFilterBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.textSoft,
  },
  chartContainer: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow,
    alignItems: 'center',
  },
  financeContent: {
    gap: spacing.md,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  reportContent: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxl,
  },
  billPanel: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    gap: spacing.md,
    padding: spacing.lg,
    ...shadow,
  },
  billPanelTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
  },
  amountRow: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  dateColumn: {
    flex: 1,
  },
  formColumn: {
    flex: 1,
  },
  monthPickerCompact: {
    minWidth: 100,
  },
  amountInput: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.lg,
    color: colors.text,
    flex: 1,
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: spacing.lg,
  },
  compactInput: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.lg,
    color: colors.text,
    fontSize: 14,
    minHeight: 52,
    paddingHorizontal: spacing.md,
    width: 132,
  },
  fullInput: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.lg,
    color: colors.text,
    fontSize: 15,
    minHeight: 50,
    paddingHorizontal: spacing.lg,
  },
  pillSection: {
    gap: spacing.sm,
  },
  pillSectionLabel: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '900',
  },
  pillEmpty: {
    color: colors.faint,
    fontSize: 13,
    fontWeight: '700',
  },
  pillScroll: {
    gap: spacing.sm,
    paddingRight: spacing.lg,
  },
  financePill: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 9999,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  financePillText: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '800',
  },
  financePillTextSelected: {
    color: '#fff',
  },
  creditCard: {
    borderRadius: 24,
    padding: spacing.xl,
    gap: spacing.lg,
    ...shadow,
    elevation: 8,
  },
  creditCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  creditCardLabel: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
    fontWeight: '700',
  },
  creditCardAmount: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: '900',
    letterSpacing: 1,
  },
  creditCardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: spacing.sm,
  },
  creditCardDate: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    fontWeight: '600',
  },
  creditCardBrand: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 14,
    fontWeight: '900',
    fontStyle: 'italic',
  },
  fab: {
    position: 'absolute',
    bottom: 32,
    right: 24,
    width: 64,
    height: 64,
    borderRadius: 32,
    ...shadow,
    elevation: 8,
    zIndex: 100,
  },
  fabGradient: {
    flex: 1,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomSheetBg: {
    backgroundColor: colors.surface,
    borderRadius: 24,
  },
  bottomSheetIndicator: {
    backgroundColor: colors.border,
    width: 48,
    height: 6,
    borderRadius: 3,
  },
  sheetTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: colors.text,
    marginBottom: spacing.md,
  },
  formActions: {
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'flex-end',
    marginTop: spacing.xl,
    paddingBottom: spacing.md,
  },
  billSummaryRow: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  billSummaryCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    flex: 1,
    padding: spacing.lg,
    ...shadow,
  },
  billSummaryLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  billSummaryValue: {
    fontSize: 22,
    fontWeight: '900',
    marginTop: spacing.xs,
  },
  billSummaryValueCompact: {
    fontSize: 17,
    fontWeight: '900',
    marginTop: 2,
  },
  reportPanel: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    gap: spacing.sm,
    overflow: 'hidden',
    padding: spacing.md,
    ...shadow,
  },
  reportHeader: {
    gap: spacing.xs,
  },
  reportTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'space-between',
  },
  reportTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  reportSubtitle: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
  },
  compactSegmented: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: 9999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 2,
    padding: 2,
  },
  compactSegmentButton: {
    alignItems: 'center',
    borderRadius: 9999,
    justifyContent: 'center',
    minHeight: 28,
    minWidth: 40,
    paddingHorizontal: 10,
  },
  compactSegmentButtonSelected: {
    backgroundColor: colors.text,
  },
  compactSegmentText: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: '900',
  },
  compactSegmentTextSelected: {
    color: colors.surface,
  },
  reportSummaryRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  reportSummaryCard: {
    alignItems: 'flex-start',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  reportFilterRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  reportDateBox: {
    flex: 1,
    minHeight: 54,
    justifyContent: 'center',
  },
  reportCustomDateRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  reportControlGrid: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  reportTotalBox: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  chartContainerCompact: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: 'hidden',
  },
  chartStyle: {
    borderRadius: radius.lg,
    marginVertical: spacing.xs,
  },
  breakdownList: {
    gap: spacing.xs,
  },
  breakdownItem: {
    backgroundColor: colors.surfaceMuted,
    borderColor: 'transparent',
    borderRadius: radius.md,
    borderWidth: 1,
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  breakdownItemSelected: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  breakdownTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  breakdownName: {
    color: colors.text,
    flex: 1,
    fontSize: 13,
    fontWeight: '900',
  },
  breakdownAmount: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  breakdownTrack: {
    backgroundColor: '#E5E7EB',
    borderRadius: 9999,
    height: 8,
    overflow: 'hidden',
  },
  breakdownFill: {
    borderRadius: 9999,
    height: '100%',
  },
  breakdownPercent: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'right',
  },

  donutStage: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    paddingBottom: 40,
    overflow: 'visible',
  },
  donutCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
  },
  donutTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  donutHint: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '700',
    marginTop: 1,
  },
  donutLabel: {
    maxWidth: 96,
    position: 'absolute',
    width: 90,
  },
  donutLabelSmall: {
    maxWidth: 60,
    position: 'absolute',
    width: 60,
  },
  donutLabelText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '500',
  },
  donutLabelPercent: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: '500',
    marginTop: 2,
  },
  treemap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    height: 200,
    marginTop: 16,
  },
  treemapEmpty: {
    alignItems: 'center',
    height: 200,
    justifyContent: 'center',
  },
  treemapTile: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 6,
    justifyContent: 'flex-end',
    padding: 8,
  },
  treemapTile0: { height: 200, width: '33%' },
  treemapTile1: { height: 200, width: '33%' },
  treemapTile2: { height: 64, width: '30%' },
  treemapTile3: { height: 64, width: '30%' },
  treemapTile4: { height: 64, width: '30%' },
  treemapTile5: { height: 64, width: '30%' },
  treemapName: { color: colors.text, fontSize: 15, fontWeight: '800' },
  treemapPercent: { color: colors.textSoft, fontSize: 13, fontWeight: '700', marginTop: 2 },
  billList: {
    gap: spacing.lg,
    paddingTop: spacing.md,
  },
  billGroup: {
    gap: spacing.sm,
    paddingLeft: spacing.md,
    borderLeftWidth: 2,
    borderLeftColor: colors.border,
    marginLeft: spacing.sm,
    position: 'relative',
  },
  billGroupTitle: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '800',
    paddingHorizontal: spacing.sm,
    marginLeft: -spacing.md - 8,
    backgroundColor: colors.bg,
    alignSelf: 'flex-start',
    paddingVertical: 4,
    borderRadius: 12,
    overflow: 'hidden',
  },
  billCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    overflow: 'hidden',
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.03)',
  },
  billCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
  },
  billIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  billIconEmoji: {
    fontSize: 20,
  },
  billCardTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  billAmount: {
    fontSize: 19,
    fontWeight: '900',
  },
  billDate: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  billCategory: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
    flexShrink: 1,
  },
  billDescription: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: spacing.xs,
  },
  billActions: {
    alignItems: 'center',
    gap: spacing.xs,
  },
  editPanel: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.lg,
    gap: spacing.md,
    marginTop: spacing.md,
    padding: spacing.md,
  },
  editActions: {
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'flex-end',
  },
  emptyBillCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.xl,
    borderStyle: 'dashed',
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.xxl,
  },
  emptyBillIcon: {
    fontSize: 36,
  },
  emptyBillText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  bentoCard: {
    width: '47.5%',
    aspectRatio: 1.05,
    borderRadius: 24,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.03)',
    backgroundColor: colors.surface,
    ...shadow,
    elevation: 8,
  },
  bentoCardLarge: {
    width: '100%',
    aspectRatio: 2.1,
    borderRadius: 24,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.03)',
    backgroundColor: colors.surface,
    ...shadow,
    elevation: 8,
  },
  bentoCardPanel: {
    width: '100%',
    borderRadius: 24,
    overflow: 'visible',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.03)',
    backgroundColor: colors.surface,
    ...shadow,
    elevation: 8,
  },
  bentoIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
});
