import type { ModuleConfig } from './types';
import { yesNo } from './options';

export const dailyModules: ModuleConfig[] = [
  {
    key: 'todos',
    title: '待办',
    subtitle: '工作和生活事项',
    endpoint: '/todos/',
    titleField: 'title',
    detailFields: ['category', 'due_date', 'due_time', 'location', 'description'],
    dateField: 'due_date',
    icon: 'checkmark-done-outline',
    accent: '#2563EB',
    emptyText: '还没有待办，先记录下一件马上要处理的事。',
    fields: [
      { key: 'title', label: '标题', type: 'text', required: true },
      { key: 'description', label: '描述', type: 'multiline' },
      { key: 'category', label: '分类', type: 'select', defaultValue: 'life', options: [
        { label: '生活', value: 'life' },
        { label: '工作', value: 'work' },
      ] },
      { key: 'due_date', label: '日期 YYYY-MM-DD', type: 'date' },
      { key: 'due_time', label: '时间', type: 'text' },
      { key: 'location', label: '地点', type: 'text' },
      { key: 'is_completed', label: '已完成', type: 'boolean', defaultValue: false, options: yesNo },
    ],
  },
  {
    key: 'moods',
    title: '心情',
    subtitle: '情绪和状态记录',
    endpoint: '/moods/',
    supportsUpdate: false,
    titleField: 'mood_label',
    detailFields: ['mood_level', 'note'],
    icon: 'happy-outline',
    accent: '#DB2777',
    emptyText: '今天还没有心情记录。',
    fields: [
      { key: 'mood_label', label: '心情标签', type: 'text', required: true },
      { key: 'mood_level', label: '心情分数 1-10', type: 'number', defaultValue: 5 },
      { key: 'note', label: '备注', type: 'multiline' },
    ],
  },
  {
    key: 'notes',
    title: '随手记',
    subtitle: '想法、线索和笔记线程',
    endpoint: '/notes/',
    titleField: 'content',
    detailFields: ['tags', 'mood_label', 'emotion'],
    icon: 'document-text-outline',
    accent: '#7C3AED',
    emptyText: '还没有笔记，先写下一条灵感。',
    fields: [
      { key: 'content', label: '内容', type: 'multiline', required: true },
      { key: 'tags', label: '标签', type: 'text' },
      { key: 'mood_level', label: '心情分数', type: 'number' },
      { key: 'mood_label', label: '心情标签', type: 'text' },
      { key: 'emotion', label: '情绪', type: 'text' },
      { key: 'parent_id', label: '父级笔记 ID', type: 'number' },
    ],
  },
  {
    key: 'worklogs',
    title: '工作日志',
    subtitle: '日常工作和活动记录',
    endpoint: '/worklogs/',
    titleField: 'record',
    detailFields: ['log_type', 'activity_name', 'event_time', 'location', 'notes'],
    icon: 'briefcase-outline',
    accent: '#0891B2',
    emptyText: '还没有工作日志。',
    fields: [
      { key: 'log_type', label: '类型', type: 'select', defaultValue: 'daily', options: [
        { label: '日常', value: 'daily' },
        { label: '活动', value: 'activity' },
      ] },
      { key: 'record', label: '记录', type: 'multiline', required: true },
      { key: 'activity_name', label: '活动名称', type: 'text' },
      { key: 'event_time', label: '事件时间 ISO', type: 'text' },
      { key: 'location', label: '地点', type: 'text' },
      { key: 'notes', label: '备注', type: 'multiline' },
    ],
  },
  {
    key: 'teachings',
    title: '课堂日志',
    subtitle: '课堂、练习和复盘',
    endpoint: '/teachings/',
    titleField: 'class_name',
    detailFields: ['course_type', 'content', 'practice_content', 'effect_rating', 'unexpected', 'reflection'],
    icon: 'school-outline',
    accent: '#4F46E5',
    emptyText: '还没有课堂日志。',
    fields: [
      { key: 'class_name', label: '班级', type: 'text', required: true },
      { key: 'course_type', label: '课程类型', type: 'text', required: true },
      { key: 'content', label: '课堂内容', type: 'multiline', required: true },
      { key: 'practice_content', label: '练习内容', type: 'multiline' },
      { key: 'effect_rating', label: '效果评分 1-10', type: 'number', defaultValue: 5 },
      { key: 'unexpected', label: '意外情况', type: 'multiline' },
      { key: 'reflection', label: '复盘', type: 'multiline' },
    ],
  },
  {
    key: 'wishlists',
    title: '愿望',
    subtitle: '想买、想去、想完成',
    endpoint: '/extras/wishlists/',
    titleField: 'title',
    detailFields: ['category', 'location', 'custom_tags', 'description', 'is_fulfilled'],
    icon: 'star-outline',
    accent: '#9333EA',
    emptyText: '还没有愿望，先写下一个想实现的念头。',
    fields: [
      { key: 'title', label: '标题', type: 'text', required: true },
      { key: 'category', label: '分类', type: 'select', defaultValue: 'shopping', options: [
        { label: '购物', value: 'shopping' },
        { label: '旅行', value: 'travel' },
      ] },
      { key: 'description', label: '描述', type: 'multiline' },
      { key: 'location', label: '地点', type: 'text' },
      { key: 'custom_tags', label: '标签', type: 'text' },
      { key: 'is_fulfilled', label: '已实现', type: 'boolean', defaultValue: false, options: yesNo },
    ],
  },
  {
    key: 'footprints',
    title: '足迹',
    subtitle: '去过的地方和照片',
    endpoint: '/extras/footprints/',
    titleField: 'location',
    detailFields: ['visit_date', 'coordinate', 'rating', 'notes'],
    dateField: 'visit_date',
    icon: 'map-outline',
    accent: '#0284C7',
    emptyText: '还没有足迹记录。',
    fields: [
      { key: 'location', label: '地点', type: 'text', required: true },
      { key: 'coordinate', label: '坐标', type: 'text' },
      { key: 'visit_date', label: '访问日期 YYYY-MM-DD', type: 'date', required: true },
      { key: 'rating', label: '评分 1-5', type: 'number' },
      { key: 'image_url', label: '图片', type: 'image' },
      { key: 'notes', label: '备注', type: 'multiline' },
    ],
  },
  {
    key: 'readings',
    title: '阅读',
    subtitle: '书籍、状态和笔记',
    endpoint: '/extras/readings/',
    titleField: 'title',
    detailFields: ['author', 'status', 'rating', 'notes'],
    icon: 'book-outline',
    accent: '#059669',
    emptyText: '还没有阅读记录。',
    fields: [
      { key: 'title', label: '书名', type: 'text', required: true },
      { key: 'author', label: '作者', type: 'text' },
      { key: 'status', label: '状态', type: 'select', defaultValue: 'to_read', options: [
        { label: '想读', value: 'to_read' },
        { label: '在读', value: 'reading' },
        { label: '读完', value: 'finished' },
      ] },
      { key: 'rating', label: '评分 1-5', type: 'number' },
      { key: 'notes', label: '笔记', type: 'multiline' },
    ],
  },
];
